services:
  mc:
    image: riscv64-minecraft-server:local
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      VERSION: "LATEST"
      MEMORY: "2G"
      ONLINE_MODE: "false"
    security_opt:
      - seccomp=unconfined
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
